import type { OnboardingConfig } from '@/lib/onboarding-config'
import { buildUniversalRoles } from '@/lib/rbac/permissions'

const demoModules = {
  dashboard: true,
  hr: true,
  inventory: true,
  finance: true,
  supply_chain: true,
  crm: true,
} as const

export const demoRestaurantWorkspace: OnboardingConfig = {
  business_type: 'Restaurant',
  modules: demoModules,
  dashboard_metrics: [
    {
      id: 'daily_revenue',
      name: 'Daily Revenue',
      description: 'Total revenue generated each day',
      type: 'currency',
      visualization: 'line_chart',
      comparison_period: 'day',
      category: 'finance',
    },
    {
      id: 'avg_order_value',
      name: 'Average Order Value',
      description: 'Average value per customer order',
      type: 'currency',
      visualization: 'stat_card',
      comparison_period: 'day',
      category: 'revenue',
    },
    {
      id: 'table_turnover_rate',
      name: 'Table Turnover Rate',
      description: 'Average number of seating cycles per table',
      type: 'ratio',
      visualization: 'bar_chart',
      comparison_period: 'day',
      category: 'operations',
    },
    {
      id: 'food_cost_percentage',
      name: 'Food Cost Percentage',
      description: 'Cost of ingredients as a percentage of sales',
      type: 'percentage',
      visualization: 'line_chart',
      comparison_period: 'week',
      category: 'finance',
    },
    {
      id: 'labor_cost_percentage',
      name: 'Labor Cost Percentage',
      description: 'Payroll cost as a percentage of sales',
      type: 'percentage',
      visualization: 'line_chart',
      comparison_period: 'week',
      category: 'hr',
    },
    {
      id: 'inventory_wastage',
      name: 'Inventory Wastage',
      description: 'Estimated ingredient wastage over time',
      type: 'number',
      visualization: 'area_chart',
      comparison_period: 'week',
      category: 'inventory',
    },
    {
      id: 'repeat_customer_rate',
      name: 'Repeat Customer Rate',
      description: 'Percentage of returning customers',
      type: 'percentage',
      visualization: 'pie_chart',
      comparison_period: 'month',
      category: 'customers',
    },
    {
      id: 'gross_margin',
      name: 'Gross Margin',
      description: 'Revenue minus direct operating costs',
      type: 'currency',
      visualization: 'stat_card',
      comparison_period: 'month',
      category: 'growth',
    },
  ],
  departments: ['Kitchen', 'Service', 'Procurement', 'Finance', 'Management'],
  shifts: [
    { name: 'Morning Shift', start: '08:00', end: '16:00' },
    { name: 'Evening Shift', start: '16:00', end: '23:30' },
  ],
  product_categories: ['Appetizers', 'Main Course', 'Beverages', 'Desserts'],
  service_types: ['Dine-in', 'Takeaway', 'Delivery'],
  roles: buildUniversalRoles(demoModules),
  setup_checklist: [
    {
      id: 'add_staff',
      title: 'Add employees and assign roles',
      description: 'Create employee records and map each to a role and department.',
      module: 'hr',
      priority: 1,
    },
    {
      id: 'add_menu_inventory',
      title: 'Set up inventory and menu categories',
      description: 'Add raw materials and map key categories used by your kitchen.',
      module: 'inventory',
      priority: 1,
    },
    {
      id: 'configure_suppliers',
      title: 'Add suppliers and procurement details',
      description: 'Set up supplier profiles and default purchase terms.',
      module: 'supply_chain',
      priority: 2,
    },
    {
      id: 'record_opening_finance',
      title: 'Record opening balances and expenses',
      description: 'Enter opening cash, recurring expenses, and revenue categories.',
      module: 'finance',
      priority: 2,
    },
    {
      id: 'define_customer_program',
      title: 'Create customer and loyalty workflow',
      description: 'Track customer interactions and loyalty/repeat customer program.',
      module: 'crm',
      priority: 3,
    },
  ],
}
