-- Workspace configuration generated by AI onboarding
create table public.workspaces (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null unique,
  business_type text not null,
  modules jsonb not null default '{}',
  dashboard_metrics jsonb not null default '[]',
  departments jsonb not null default '[]',
  shifts jsonb,
  product_categories jsonb,
  service_types jsonb,
  roles jsonb not null default '[]',
  setup_checklist jsonb not null default '[]',
  created_at timestamp with time zone default now()
);

alter table public.workspaces enable row level security;

create policy "Users can view own workspace" on public.workspaces
  for select using (auth.uid() = user_id);

create policy "Users can insert own workspace" on public.workspaces
  for insert with check (auth.uid() = user_id);

create policy "Users can update own workspace" on public.workspaces
  for update using (auth.uid() = user_id);
